main/urls.py
import django
from django.urls import path
from . import views
from django.contrib.auth.views import login_required
from .views import index, user_login, login, LogoutView, RegisterDoneView, RegisterUserView
from django.conf import settings
from django.conf.urls.static import static

app_name='main'

urlpatterns = [
    path('', views.hello, name='hello'),
    path('login/', user_login, name='login'),
    path('profile/', views.profile, name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('change_pass/', views.change_pass, name='change_pass'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

secondsite/urls.py
from django.contrib import admin
from django.urls import path, include

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.contrib.auth.models import AbstractUser, User
from django.db import models
from django.dispatch import Signal
# from .utilities import send_activation_notification
# Create your models here.


class Customers(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=30)
    phone = models.CharField(max_length=50, db_index=True, unique=True)
    rassilka = models.BooleanField(default=True, verbose_name='Согласны ли вы получать рассылку?')

    def __str__(self):
        return 'Пользователь %s' % (self.name)


class DataModelUser(models.Model):
    login = models.CharField(unique=True, max_length=50)
    password = models.CharField(max_length=100)



# class AdvUser(models.Model):
#     is_activated = models.BooleanField(default=True)
#     user = models.OneToOneField(User, on_delete=models.CASCADE)

# user_registrated = Signal(providing_args=['instance'])
#
# def user_registrated_dispatcher(sender, **kwargs):
#     send_activation_notification(kwargs['instance'])
#
# user_registrated.connect(user_registrated_dispatcher)


class CustomUser(AbstractUser):
    pass

main/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from .models import *
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
# from .models import user_registrated


class CusForm(forms.ModelForm):
    email = forms.EmailField(label='Почтовый ящик', max_length=50)
    name = forms.CharField(label='Ваше имя', max_length=25)
    phone = forms.CharField(label='Ваш номер телефона', max_length=12)
    rassilka = models.BooleanField(default=True, verbose_name='Согласны ли вы получать рассылку?')

    class Meta:
        model = Customers
        fields = ['email', 'name', 'phone', 'rassilka']


class UserForm(forms.Form):
    login = forms.CharField(label='Имя пользователя', max_length=50)
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)


class RegisterUserForm(forms.ModelForm):
    username = forms.CharField(required=True, label='Имя пользователя')
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    password1 = forms.CharField(required=True, widget=forms.PasswordInput, label='Введите пароль')
    password2 = forms.CharField(widget=forms.PasswordInput, required=True, label='Повторите ваш пароль')
    first_name = forms.CharField(required=True, label='Ваше имя')
    last_name = forms.CharField(required=True, label='Ваша фамилия')
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 'password2', 'first_name', 'last_name']

    def clean_password(self):
        password1=self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1


    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2':ValidationError('Введеные пароли не совпадают', code='password_mismatch')}
            raise ValidationError(errors)


    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = True
        user.is_activated = True
        if commit:
            user.save()
        return user


class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(widget=forms.PasswordInput, max_length=75, label='Введите текущий пароль')
    new_password1 = forms.CharField(widget=forms.PasswordInput, max_length=75, label='Введите новый пароль')
    new_password2 = forms.CharField(widget=forms.PasswordInput, max_length=75, label='Введите повторно новый пароль')
class Meta:
    model = CustomUser
    fields = ['old_password', 'new_password1', 'new_password2']

main/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views.generic import CreateView
from django.contrib.auth import login
from django.contrib.auth.views import LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CusForm, DataModelUser
from django.contrib.auth import authenticate, login
from .forms import *
from django.views.generic.base import TemplateView
from django.urls import reverse, reverse_lazy
from django.core.signing import BadSignature
# from .utilities import signer
# Create your views here.


def index(request):
    return render(request, "index.html")


def hello(request):
    form = CusForm(request.POST)
    abc = {'form':form}
    if request.method == 'POST' and form.is_valid():
        data=form.cleaned_data
        ready_form = form.save()
    return render(request, 'main/index.html', abc)


def user_login(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(request, username=data['login'], password=data['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('main:profile')
                else:
                    return HttpResponse('Авторизация провалена. Повторите попытку')
            else:
                return HttpResponse('Введены некорректные данные.')
    else:
        form = UserForm()
    return render(request, 'main/login.html', {'form': form})

''' https://pocoz.gitbooks.io/django-v-primerah/content/glava-4-sozdanie-social-website/ispolzovanie-django-authentication-framework/sozdanie-log-in-view.html'''


@login_required
def profile(request):
    return render(request, 'main/profile.html')


class LogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'

class RegisterUserView(CreateView):
    model = CustomUser
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')


class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'


@login_required
def change_pass(request):
    if request.method == 'POST':
        passwords = request.POST
        user = request.user
        old_password = passwords['old_password']
        new_password1 = passwords['new_password1']
        new_password2 = passwords['new_password2']
        if check_password(old_password, user.password):
            if new_password1 == new_password2:
                user.set_password(new_password1)
                user.save()
                message = 'Ваш пароль успешно изменен.'
                return render(request, 'main/index.html', context={'message': message})
            else:
                error = 'Пароли не совпадают'
                return render(request, 'main/change_pass.html', context={'error': error})
    form = ChangePasswordForm()
    context = {'form': form}
    return render(request, 'main/change_pass.html', context)

main/templates/main/index.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
	<title>BestPortalZXC</title>
	<!-- META TAGS -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'main/img/BPsmall.png' %}">
	<meta name="author" content="Brodo">
	<meta name="description" content="Best portal ever">

	<!-- STYLES -->
	<link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'main/css/ionicons.min.css' %}">
	<link rel="stylesheet" href="{% static 'main/css/flexslider.css' %}">
	<link rel="stylesheet" href="{% static 'main/css/animsition.min.css' %}">
	<link rel="stylesheet" href="{% static 'main/css/animate.css' %}">
	<link rel="stylesheet" href="{% static 'main/css/style.css' %}">
</head>
<body class="animsition">
	<!-- HEADER  -->
	<header class="main-header">
		<div class="container">
			<div class="menu">
				<!-- desktop navbar -->
				<nav class="desktop-nav">
					<ul class="first-level">
						<li><a href="{% url 'main:hello' %}" class="animsition-link">Главная</a></li>
						<li><a href="index.html" class="animsition-link">Актуальная информация</a></li>
						<li><a href="index.html" class="animsition-link">Ранний доступ</a></li>
						<li><a href="index.html" class="animsition-link">Контакты</a></li>
				</nav>
			</div>
		</div>
	</header>

	<!-- HERO SECTION  -->
	<div class="site-hero">
		<ul class="slides">
			<li>
				<div><span class="small-title uppercase montserrat-text">BestPortalZXC</span></div>
				<div class="big-title uppercase montserrat-text">Интернет портал</div>
				<p>Интернет-портал находится на стадии разработки.</br>Дата ее начала: 20.01.2020</p>
			</li>
			<li>
				<div><span class="small-title uppercase montserrat-text">BestPortalZXC</span></div>
				<div class="big-title uppercase montserrat-text">Помощь в разработке</div>
				<p>Если вы хотите помочь в разработке нашего портала, просим связаться с нами, контакты можно найти щелкнув по специальному разделу меню. </p>
			</li>
		</ul>
	</div>

	<!-- NEWS AND REG -->
	<div class="container">
		<div class="agency">
			<div class="col-md-5 col-sm-12">
				<div class="row">
					<img src="{% static 'main/img/agency.jpg' %}" alt="image">
				</div>
			</div>
			<div class="col-md-offset-1 col-md-6 col-sm-12">
				<div class="row">
					<div class="section-title">
						<span>Подписка на новости</span>
					</div>
					<p>
						Если вы желаете получать актуальные новости и узнать дату открытия портала раньше всех - оформите заявление по указанной ниже форме: 
					</p>
 	<form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn">Отправить</button>
    </form>
				</div>
			</div>
		</div>
	</div>


	<!-- BETA TESTING -->
	<section class="services">
		<div class="container">
			<div class="row">
				<div class="section-title">
					<span>Ранний доступ</span>
					<p>Любой пользователь может поучаствовать в бета-тестировании нашего портала и получить ранний доступ.
					   Если вы желаете поучавствовать в бета-тестировании - Вам необходимо зарегистрироваться, если вы уже
				       загеристрированны - авторизоваться</p>
					{% if user.is_authenticated %}
					<a href="{% url 'main:profile' %}" class="btn green" style="float:left;margin-top:15px; margin-left: -100px;"><span>Мой профиль</span></a>
					<a href="{% url 'main:change_pass' %}" class="btn green" style="float: center; margin-top: 15px"><span>Сменить пароль</span></a>
					<a href="{% url 'main:logout' %}" class="btn green" style="float:right;margin-top: 15px; margin-right: -40px"><span>Выйти</span></a>
					{% else %}
					<a href="{% url 'main:register' %}" class="btn green" style="float:left;margin-top:30px"><span>Регистрация</span></a>
					<a href="{% url 'main:login' %}" class="btn green" style="float:right;margin-top:30px"><span>Авторизация</span></a>
					{% endif %}
				</div>
			</div>

			
	<!-- DONATION  -->
	<section class="green-section wow fadeInUp" style="padding:50px 0">
		<div class="container">
			<div class="col-md-6 col-sm-12">
				<div class="аrow">
					<span class="white-text montserrat-text uppercase" style="font-size:30px;display:block;">
						Помочь проекту материально вы можете нажав по кнопке
					</span>
					<a href="#" class="btn white" style="margin-top:30px"><span>Спасибо</span></a>
				</div>
			</div>

			<div class="col-md-6 col-sm-12">
				<div class="row">
					<div class="white-section" style="padding:20px">
						<span class="montserrat-text uppercase" style="font-size:24px">Если вам нужна помощь или консультация</span>
						<p>
							Просто напишите тут свой адрес электронной почты и наши сотрудники свяжутся с вами.
						</p>
						<form action="#" method="post">
							<div class="input_1">
								<input type="text" name="email">
								<span>Адрес эл. почты</span>
							</div>
							<button type="submit" class="btn green" style="margin-top:20px"><span>Отправить</span></button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>


	<!-- FOOTER -->
	<footer class="main-footer wow fadeInUp">
		<div class="container">
			<div class="col-md-8 col-sm-12">
				<div class="row">
					<nav class="footer-nav">
						<ul>
							<li><a href="index.html" class="animsition-link link">Главная</a></li>
							<li><a href="about.html" class="animsition-link link">Актуальная информация</a></li>
							<li><a href="services.html" class="animsition-link link">Ранний доступ</a></li>
							<li><a href="contact.html" class="animsition-link link">Контакты</a></li>
						</ul>
					</nav>
				</div>
			</div>

			<div class="col-md-4 col-sm-12" style="text-align:right">
				<div class="row">
					<div class="uppercase gray-text">
						Created by Brodo & danyamaestro &copy;2021.</br> all rights reserved.
					</div>
					<ul class="social-icons" style="margin-top:30px;float:right">
						<li><a href="#"><i class="icon ion-social-facebook"></i></a></li>
						<li><a href="#"><i class="icon ion-social-twitter"></i></a></li>
						<li><a href="#"><i class="icon ion-social-youtube"></i></a></li>
						<li><a href="#"><i class="icon ion-social-linkedin"></i></a></li>
						<li><a href="#"><i class="icon ion-social-pinterest"></i></a></li>
						<li><a href="#"><i class="icon ion-social-instagram"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
	</footer>

	<!-- SCRIPTS -->
	<script type="text/javascript" src="{% static 'main/js/jquery-2.1.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'main/js/isotope.pkgd.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'main/js/jquery.flexslider.js' %}"></script>
	<script type="text/javascript" src="{% static 'main/js/smoothScroll.js' %}"></script>
	<script type="text/javascript" src="{% static 'main/js/jquery.animsition.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'main/js/wow.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'main/js/main.js' %}"></script>

	<script type="text/javascript" charset="utf-8">
		$(window).load(function() {
			new WOW().init();

			// initialise flexslider
			$('.site-hero').flexslider({
				animation: "fade",
				directionNav: false,
				controlNav: false, 
				keyboardNav: true,
				slideToStart: 0,
				animationLoop: true,
				pauseOnHover: false,
				slideshowSpeed: 4000, 
			});
		});
	</script>
</body>
</html>

main/templates/main/logout.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
	<title>Выход</title>
	<!-- META TAGS -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'main/img/BPsmall.png' %}">

	<!-- STYLES -->
	<link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'main/css/ionicons.min.css' %}">
	<link rel="stylesheet" href="{% static 'main/css/animsition.min.css' %}">
	<link rel="stylesheet" href="{% static 'main/css/flexslider.css' %}">
	<link rel="stylesheet" href="{% static 'main/css/animate.css' %}">
	<link rel="stylesheet" href="{% static 'main/css/style.css' %}">
</head>
<body class="animsition">
	<!-- HEADER  -->
	<header class="main-header">
		<div class="container">
			<div class="menu">
				<!-- desktop navbar -->
				<nav class="desktop-nav">
					<ul class="first-level">
						<li><a href="index.html" class="animsition-link">Главная</a></li>
						<li><a href="index.html" class="animsition-link">Актуальная информация</a></li>
						<li><a href="index.html" class="animsition-link">Ранний доступ</a></li>
						<li><a href="index.html" class="animsition-link">Контакты</a></li>
					</ul>
				</nav>
			</div>
		</div>
	</header>

	<!-- HERO SECTION  -->
{% block content %}
	<div class="site-hero_2">
		<div class="page-title">
			<div class="big-title montserrat-text uppercase">Вы успешно вышли со своего профиля</div>
					<a href="{% url 'main:login' %}" class="btn green" style="float:left;margin-top:30px"><span>Авторизация</span></a>
					<a href="{% url 'main:hello' %}" class="btn green" style="float:right;margin-top:30px"><span>Главная</span></a>
		</div>
	</div>
{% endblock %}

	<!-- DONATION  -->
	<section class="green-section wow fadeInUp" style="padding:50px 0">
		<div class="container">
			<div class="col-md-6 col-sm-12">
				<div class="row">
					<span class="white-text montserrat-text uppercase" style="font-size:30px;display:block;">
						Помочь проекту материально вы можете нажав по кнопке
					</span>
					<a href="#" class="btn white" style="margin-top:30px"><span>Спасибо</span></a>
				</div>
			</div>

			<div class="col-md-6 col-sm-12">
				<div class="row">
					<div class="white-section" style="padding:20px">
						<span class="montserrat-text uppercase" style="font-size:24px">Если вам нужна помощь или консультация</span>
						<p>
							Просто напишите тут совй номер телефона и наши сотрудники свяжутся с вами.
						</p>
						<form action="#" method="post">
							<div class="input_1">
								<input type="text" name="email">
								<span>+375 29 1234 56 78</span>
							</div>
							<button type="submit" class="btn green" style="margin-top:20px"><span>Отправить</span></button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>


	<!-- FOOTER -->
	<footer class="main-footer wow fadeInUp">
		<div class="container">
			<div class="col-md-8 col-sm-12">
				<div class="row">
					<nav class="footer-nav">
						<ul>
							<li><a href="index.html" class="animsition-link link">Главная</a></li>
							<li><a href="about.html" class="animsition-link link">Актуальная информация</a></li>
							<li><a href="services.html" class="animsition-link link">Ранний доступ</a></li>
							<li><a href="contact.html" class="animsition-link link">Контакты</a></li>
						</ul>
					</nav>
				</div>
			</div>

			<div class="col-md-4 col-sm-12" style="text-align:right">
				<div class="row">
					<div class="uppercase gray-text">
						Created by Brodo & Danyamaestro &copy;2021.</br> all rights reserved.
					</div>
					<ul class="social-icons" style="margin-top:30px;float:right">
						<li><a href="#"><i class="icon ion-social-facebook"></i></a></li>
						<li><a href="#"><i class="icon ion-social-twitter"></i></a></li>
						<li><a href="#"><i class="icon ion-social-youtube"></i></a></li>
						<li><a href="#"><i class="icon ion-social-linkedin"></i></a></li>
						<li><a href="#"><i class="icon ion-social-pinterest"></i></a></li>
						<li><a href="#"><i class="icon ion-social-instagram"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
	</footer>

	<!-- SCRIPTS -->
	<script type="text/javascript" src="{% static 'main/js/jquery-2.1.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'main/js/isotope.pkgd.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'main/js/jquery.flexslider.js' %}"></script>
	<script type="text/javascript" src="{% static 'main/js/smoothScroll.js' %}"></script>
	<script type="text/javascript" src="{% static 'main/js/jquery.animsition.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'main/js/wow.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'main/js/main.js' %}"></script>

	<script type="text/javascript" charset="utf-8">
		$(window).load(function() {
			new WOW().init();

			// initialise flexslider
			$('.site-hero').flexslider({
				animation: "fade",
				directionNav: false,
				controlNav: false, 
				keyboardNav: true,
				slideToStart: 0,
				animationLoop: true,
				pauseOnHover: false,
				slideshowSpeed: 4000, 
			});
		});
	</script>
</body>
</html>

main/templates/main/register_done.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
	<title>Регистрация завершена!</title>
	<!-- META TAGS -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'main/img/BPsmall.png' %}">

	<!-- STYLES -->
	<link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'main/css/ionicons.min.css' %}">
	<link rel="stylesheet" href="{% static 'main/css/animsition.min.css' %}">
	<link rel="stylesheet" href="{% static 'main/css/flexslider.css' %}">
	<link rel="stylesheet" href="{% static 'main/css/animate.css' %}">
	<link rel="stylesheet" href="{% static 'main/css/style.css' %}">
</head>
<body class="animsition">
	<!-- HEADER  -->
	<header class="main-header">
		<div class="container">
			<div class="menu">
				<!-- desktop navbar -->
				<nav class="desktop-nav">
					<ul class="first-level">
						<li><a href="index.html" class="animsition-link">Главная</a></li>
						<li><a href="index.html" class="animsition-link">Актуальная информация</a></li>
						<li><a href="index.html" class="animsition-link">Ранний доступ</a></li>
						<li><a href="index.html" class="animsition-link">Контакты</a></li>
					</ul>
				</nav>
			</div>
		</div>
	</header>

	<!-- HERO SECTION  -->
	<div class="site-hero_2">
		<div class="page-title">
			{% block title %}
			<div class="big-title montserrat-text uppercase">Регистрация успешно выполнена!</div>
			{% endblock %}
			{% block content %}
					<a href="{% url 'main:login' %}" class="btn green" style="float:left;margin-top:30px"><span>Авторизация</span></a>
					<a href="{% url 'main:hello' %}" class="btn green" style="float:right;margin-top:30px"><span>Главная</span></a>
			{% endblock %}
		</div>
	</div>

	<!-- DONATION  -->
	<section class="green-section wow fadeInUp" style="padding:50px 0">
		<div class="container">
			<div class="col-md-6 col-sm-12">
				<div class="row">
					<span class="white-text montserrat-text uppercase" style="font-size:30px;display:block;">
						Помочь проекту материально вы можете нажав по кнопке
					</span>
					<a href="#" class="btn white" style="margin-top:30px"><span>Спасибо</span></a>
				</div>
			</div>

			<div class="col-md-6 col-sm-12">
				<div class="row">
					<div class="white-section" style="padding:20px">
						<span class="montserrat-text uppercase" style="font-size:24px">Если вам нужна помощь или консультация</span>
						<p>
							Просто напишите тут совй номер телефона и наши сотрудники свяжутся с вами.
						</p>
						<form action="#" method="post">
							<div class="input_1">
								<input type="text" name="phone">
								<span>+375 29 123 45 67</span>
							</div>
							<button type="submit" class="btn green" style="margin-top:20px"><span>Отправить</span></button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>


	<!-- FOOTER -->
	<footer class="main-footer wow fadeInUp">
		<div class="container">
			<div class="col-md-8 col-sm-12">
				<div class="row">
					<nav class="footer-nav">
						<ul>
							<li><a href="index.html" class="animsition-link link">Главная</a></li>
							<li><a href="about.html" class="animsition-link link">Актуальная информация</a></li>
							<li><a href="services.html" class="animsition-link link">Ранний доступ</a></li>
							<li><a href="contact.html" class="animsition-link link">Контакты</a></li>
						</ul>
					</nav>
				</div>
			</div>

			<div class="col-md-4 col-sm-12" style="text-align:right">
				<div class="row">
					<div class="uppercase gray-text">
						Created by Brodo & Danyamaestro &copy;2021.</br> all rights reserved.
					</div>
					<ul class="social-icons" style="margin-top:30px;float:right">
						<li><a href="#"><i class="icon ion-social-facebook"></i></a></li>
						<li><a href="#"><i class="icon ion-social-twitter"></i></a></li>
						<li><a href="#"><i class="icon ion-social-youtube"></i></a></li>
						<li><a href="#"><i class="icon ion-social-linkedin"></i></a></li>
						<li><a href="#"><i class="icon ion-social-pinterest"></i></a></li>
						<li><a href="#"><i class="icon ion-social-instagram"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
	</footer>

	<!-- SCRIPTS -->
	<script type="text/javascript" src="{% static 'main/js/jquery-2.1.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'main/js/isotope.pkgd.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'main/js/jquery.flexslider.js' %}"></script>
	<script type="text/javascript" src="{% static 'main/js/smoothScroll.js' %}"></script>
	<script type="text/javascript" src="{% static 'main/js/jquery.animsition.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'main/js/wow.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'main/js/main.js' %}"></script>

	<script type="text/javascript" charset="utf-8">
		$(window).load(function() {
			new WOW().init();

			// initialise flexslider
			$('.site-hero').flexslider({
				animation: "fade",
				directionNav: false,
				controlNav: false, 
				keyboardNav: true,
				slideToStart: 0,
				animationLoop: true,
				pauseOnHover: false,
				slideshowSpeed: 4000, 
			});
		});
	</script>
</body>
</html>

main/templates/main/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Красота</title>
</head>
<body>
<h3 style="text-align:center;">Всем привет меня зовут Майя</h3>
<font color="red"; size="60px">Hello world</font>
<a href="https://vk.com/neverhappyagain/"><button>Привет Майя</button></a>
</body>
</html>